# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/favicon.png"
    high_res_favicon: "/img/favicon.png"
    apple_touch_icon: "/img/favicon.png"
    keywords:
    site_verification:
        google:
        baidu: J5O1G13OwG

    # Enable generate structured-data as JSON+LD for SEO or not.
    #        Set as 'false' if it cause some wrong when `hexo g`.
    structured_data: true

# Jump Links Settings
url:
    rss:
    daily_pic: "http:www.xposean.xin/about"
    logo: "/"


# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
#scheme: Paradox
scheme: Isolation

# UI & UX: slogan, color, effect
uiux:
    slogan:
      - "做一个刚刚好的前端仔"
      - "——关于我"
    theme_color: "#03A9F4"
    theme_sub_color: "#00838F"
    hyperlink_color: "#00838F"
    button_color: "#757575"
    android_chrome_color: "#0097A7"
    nprogress_color: "#29d"
    nprogress_buffer: "800"

# JS Effect Switches
js_effect:
    fade: true
    smoothscroll: true

# Reading experience
reading:
    entry_excerpt: 80

# Thumbnail Settings
thumbnail:
    purecolor:
    random_amount: 19

# Background Settings
# bing available parameter:
#     new | color= | type=
#         color available value: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow
#         type available value: A (animal), C (culture), N (nature), S (space), T (travel)
background:
    purecolor: "#ffffff"
#    bgimg: "/img/bg.png"
    bing:
        enable: false
        parameter:
            color: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow.
            type: A (动物), C (人文), N (自然), S (太空), T (旅行).

# Images Settings
img:
    logo: "/img/logo.png"
    avatar: "/img/avatar.png"
    daily_pic: "/img/daily_pic.png"
    sidebar_header: "/img/sidebar_header.png"
    random_thumbnail: "/img/random/material-"
    footer_image:
        upyun_logo:
            link: "https://www.upyun.com/"
            src: "/img/upyun_logo.svg"

# Custom Fonts
#   family: the font-family which will be used in the theme
#   host: uri of fonts host.
#       Available value of "host": google | baomitu | ustc | custom
fonts:
    family: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif
    use: baomitu
    custom_font_host:

# Card Elevation Level
card_elevation: 2

# Copyright
# Specify the date when the site was setup.
#   For example, if you set it as 2015, then footer will show '© 2015 - 2017'
copyright_since:

# Qrcode for redirect at other device
#   use: choose which method to generate the qrcode for each posts.
#       Available value of "use": plugin | online
#           - When use "plugin", you need to install the hexo-helper-qrcode.
#           - When use "online", the qrcode will be generated by 'pan.baidu.com' in China.
qrcode:
    enable: true
    use: online


# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# TOC Button

toc:
#   use: choose whether the line_number of toc will show or not.
#       Available value of "linenumber": true | false
    linenumber: true

# SNS Menu
sns:
    email: qq843095666@gmail.com
    #facebook: "https://www.facebook.com/facebook"
#    twitter: "https://twitter.com/twitter"
#    googleplus: "https://www.google.com/"
    weibo: Anonlyy
    instagram:
    tumblr:
    github: https://github.com/Anonlyy
    linkedin:
    zhihu:
    bilibili:
    telegram: 13160663115
    qq: 843095666

# SNS Share Switch
sns_share:
    twitter: false
    facebook: false
    googleplus: false
    weibo: true
    linkedin: false
    qq: true
    telegram: false

# Sidebar Customize
sidebar:
    dropdown:
        Email Me:
            link: "#"
            icon: email
    homepage:
        use: true
        icon: home
        divider: false
    archives:
        use: true
        icon: inbox
        divider: false
    categories:
        use: true
        icon: chrome_reader_mode
        divider: false
    pages:
        关于我:
            link: "/about"
            icon: person
            divider: false
        照片集:
            link: "/gallery"
            icon: photo
            divider: false

    article_num:
        use: false
        divider: false
    footer:
        divider: true
        theme: true
        support: false
        feedback: false
        material: false


# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------

# MaterialCDN
# When you set 'use' as true, the needed css, js, font file will have a new src.
# The new src will have the base domain you configured in 'base'.
materialcdn: 
    use: 
    base: 

# Comment Systems
# Available value of "use":
#     disqus | disqus_click | changyan | 163gentie
comment:
    use:
    shortname: # duoshuo or disqus shortname
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    gentie_productKey: 

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: local
#    swiftype_key:

# Analytics Systems
# Available value:
#     baidu | google | cnzz
analytics:
    use:
    site_id:

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: false
    all_site_uv: false
    post_pv: false
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"